### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by Punctuality** [dongxiangjue/Co2PT#1]
Hello,

I found you [paper](https://arxiv.org/abs/2310.12490) though [PapersWithCode](https://paperswithcode.com/paper/co-2-pt-mitigating-bias-in-pre-trained) and there's seems to be no code present in this repo as of this moment.

Is that intentional? Can we expect to have one sometime in the near future?

**Comment by dongxiangjue** [comment]
Hi,

Thanks for the reminder! I just uploaded the code. If any details are missing, I'll update them. Thanks!

Best,

**Comment by Punctuality** [comment]
Thank you for quick response, I'll then close this issue then. If there will be something else, that'll be another _ticket_
