### ISSUE TITLE
Inquiry Regarding Dataset

### ISSUE THREAD

**Issue by polyn0** [dongxiangjue/Co2PT#2]
Hello,

I'm curious if there are any plans to provide the dataset and preprocessing code for the project. 

Thank you.

**Comment by dongxiangjue** [comment]
Hi,

Thank you for reminding me about the dataset. I have shared it on Google Drive and updated the README accordingly.

Thanks!

**Comment by polyn0** [comment]
Like your project! Thanks a lot!
